import { createRoot } from "react-dom/client";
import { HelmetProvider } from "react-helmet-async";
import App from "./App.tsx";
import "./index.css";
import { initThemeEarly } from "./hooks/useTheme";

initThemeEarly();

// Guard: never register the PWA service worker inside Lovable's preview iframe
const isInIframe = (() => {
  try {
    return window.self !== window.top;
  } catch {
    return true;
  }
})();
const isPreviewHost =
  window.location.hostname.includes("id-preview--") ||
  window.location.hostname.includes("lovableproject.com");

if (isPreviewHost || isInIframe) {
  // Aggressively unregister any SW that may have been installed in a previous build
  if ("serviceWorker" in navigator) {
    navigator.serviceWorker.getRegistrations?.().then((regs) => {
      regs.forEach((r) => r.unregister());
    });
  }
} else {
  // Production / standalone: register the SW generated by vite-plugin-pwa
  import("virtual:pwa-register")
    .then(({ registerSW }) => {
      const updateSW = registerSW({
        immediate: true,
        onNeedRefresh() {
          import("sonner").then(({ toast }) => {
            toast("Nouvelle version disponible", {
              duration: Infinity,
              action: {
                label: "Mettre à jour",
                onClick: () => updateSW(true),
              },
            });
          });
        },
      });
    })
    .catch(() => {
      /* SW not available (e.g. dev) — ignore */
    });
}

createRoot(document.getElementById("root")!).render(
  <HelmetProvider>
    <App />
  </HelmetProvider>
);
